NEW: ‹ConditionalWorkSequence:5 (2)›
   : │  id: 5
   : │  call count: 0
   : │  EVENT: startup
   : └1╴... done.
EVENT: startup
END: startup
TRACE Create OnEvtHandler: send¦logger
TRACE NewHandler 6
NEW: ‹ConditionalWorkSequence:7 (2)›
   : │  id: 7
   : │  call count: 0
   : │  EVENT: wait¦start¦5.0¦shutdown
   : └1╴... done.
EVENT: wait¦start¦5.0¦shutdown
END: wait¦start¦5.0¦shutdown
NEW: ‹ConditionalWorkSequence:8 (2)›
   : │  id: 8
   : │  call count: 0
   : │  EVENT: rpc¦connect¦foo¦n1
   : └1╴... done.
EVENT: rpc¦connect¦foo¦n1
END: rpc¦connect¦foo¦n1
TEST 1 (Name('event',),)
4 Logging error
ERROR (<type 'exceptions.KeyError'>, KeyError('TEST',), <traceback obj>)
TEST 1 (Name('job',),)
TEST 1 (Name('log',),)
TEST 1 (Name('module',),)
TEST 1 (Name('net', 'connection'),)
TEST 1 (Name('net', 'server'),)
TEST 1 (Name('on',),)
TEST 1 (Name('parser',),)
TEST 1 (Name('rpc', 'connection'),)
TEST 1 (Name('rpc', 'server'),)
TEST 1 (Name('state',),)
TEST 1 (Name('wait',),)
TEST 1 (Name('worker',),)
TEST 1 .
TEST 1 (Name(u'foo',),)
TEST 1 .
TEST 1 (u'', u'\u2039Collected RPCserver:foo\u203a')
TEST 1 (u'name', u'foo')
TEST 1 (u'host', u'')
TEST 1 (u'port', u'56478')
TEST 1 (u'server', u'<homevent.gevent_rpyc.GeventServer obj>')
TEST 1 .
TEST 1 (u'', u'\u2039Collected namedRPC:foo\xa6n1\u203a')
TEST 1 (u'name', u'foo\xa6n1')
TEST 1 (u'local host', u'::ffff:127.0.0.1')
TEST 1 (u'local port', u'56478')
TEST 1 (u'remote host', u'::ffff:127.0.0.1')
TEST 1 (u'remote port', u'55207')
TEST 1 .
Traceback (most recent call last):
  File "../modules/rpc.py", line 307, in exposed_command
    return CommandProcessor(parent=self,ctx=self.ctx).simple_statement(args)
  File "../modules/rpc.py", line 100, in simple_statement
    fn = self.lookup(args)
  File "/home/smurf/homevent/homevent/interpreter.py", line 78, in lookup
    fn = me.lookup(event)
  File "/home/smurf/homevent/homevent/statement.py", line 242, in lookup
    raise UnknownWordError(args,self)
UnknownWordError: Cannot find word <fuubar This is not found.> in <Global>
NEW: ‹WorkSequence:10 (2)›
   : │  id: 10
   : │  call count: 0
   : │  Cannot find word ‹fuubar This is not found.› in ‹Global›
   : └1╴... done.
Traceback (most recent call last):
  File "../modules/rpc.py", line 307, in exposed_command
    return CommandProcessor(parent=self,ctx=self.ctx).simple_statement(args)
  File "../modules/rpc.py", line 100, in simple_statement
    fn = self.lookup(args)
  File "/home/smurf/homevent/homevent/interpreter.py", line 78, in lookup
    fn = me.lookup(event)
  File "/home/smurf/homevent/homevent/statement.py", line 242, in lookup
    raise UnknownWordError(args,self)
UnknownWordError: Cannot find word <fuubar This is not found.> in <Global>
END: UnknownWordError
TEST 1 YES Got an error
DEBUG This is logged.
TEST 1 The value is: Test123
NEW: ‹ConditionalWorkSequence:11 (3)›
   : │  id: 11
   : │  call count: 0
   : │  IEVENT: send¦logger
   : ├1╴on send logger ‹OnEventHandler›
   : │  prio: 51
   : │  step: log DEBUG hello This is a test ‹LogHandler›
   : └2╴... done.
IEVENT: send¦logger
RUN: on send logger ‹OnEventHandler›
   : prio: 51
   : step: log DEBUG hello This is a test ‹LogHandler›
 at: ‹ConditionalWorkSequence:11 (3)› (step 1)
 ev: IEVENT: send¦logger
DEBUG hello This is a test
END: send¦logger
2014-11-15 18:45:03.879687 shutdown: Forced timer done 
NEW: ‹ConditionalWorkSequence:12 (2)›
   : │  id: 12
   : │  call count: 0
   : │  EVENT: wait¦done¦5.1¦shutdown
   : └1╴... done.
EVENT: wait¦done¦5.1¦shutdown
END: wait¦done¦5.1¦shutdown
NEW: ‹ConditionalWorkSequence:13 (2)›
   : │  id: 13
   : │  call count: 0
   : │  EVENT: wait¦start¦6.1¦foo¦b
   : └1╴... done.
EVENT: wait¦start¦6.1¦foo¦b
END: wait¦start¦6.1¦foo¦b
2014-11-15 18:45:04.889933 foo¦b: Forced timer done 
NEW: ‹ConditionalWorkSequence:14 (2)›
   : │  id: 14
   : │  call count: 0
   : │  EVENT: wait¦done¦6.1¦foo¦b
   : └1╴... done.
EVENT: wait¦done¦6.1¦foo¦b
END: wait¦done¦6.1¦foo¦b
